#!/bin/python3

from tkinter import *
from tinytag import TinyTag
import tkinter as tk
from decimal import Decimal
from mutagen import File
from PIL import Image, ImageTk
from pathlib import Path
import time, pygame, os, subprocess, sys, random

_arg_lst = []
if len(sys.argv) > 1:
	_get_files = 0

	for i in sys.argv[1:]:
		_arg_lst.append(i)

	if "--help" in _arg_lst:
		print("usage; graphite [--key=val]")
		print("options;")
		print("    --dir         [directory for music]")
		print("    --shuffle     [immediately set shuffle on]")
		print("    --repeat      [immediately set repeat on]")
		print("    --help        [display this help and exit]\n")
		sys.exit()

	for i in _arg_lst:
		if i.startswith("--dir="):
			_music_user_directory = i.split("--dir=")[1]
			_get_files = 1
		elif i == "--shuffle":
			switchState(None, "shuffle")
		elif i == "--repeat":
			switchState(None, "repeat")

	if _get_files == 1:
		getFiles(5,False,None)
	else:
		getFiles(0,False,None)


subprocess.run('clear')

pygame.init()
pygame.mixer.init()

# these are earlier created with install.sh
# i lowkey had a mini heart attack, thinking these weren't created by default
# i'm dumb

_home = Path.home()
_graphite = _home / '.config' / 'graphite'
_config = _graphite / 'graphite.conf'
_playlist_folder = _graphite / 'playlists'
_status_file = _graphite / 'status.txt'

def modifyStatus(nowplaying):
	with open(_status_file, 'w') as stat:
		stat.write(f'{nowplaying}\n')

def readFromConfig():
	global _notifications
	with open(_config, 'r') as cfg:
		for line in cfg:
			if (' = ' not in line and ';' not in line):
				continue
			key, value = line.split(' = ', 1)
			key = key.strip()
			value = value.strip()
			value = value.strip(';')
		
			if key == 'foreground':
				_fg = str(value)
			elif key == 'background':
				_bg = str(value)
			elif key == 'font':
				_fnt = str(value)
			elif key == 'font size':
				_fnt_size = int(value)
			elif key == 'directory to choose music from':
				_music_user_directory = str(value)
			elif key == 'logo2 directory':
				_logo2_directory = value
			elif key == 'logo3 directory':
				_logo3_directory = value
			elif key == 'send notifs on song play':
				_notifications = int(value)
			elif key == 'dir x':
				_def_dirx = value
			elif key == 'play x':
				_def_playx = value
			elif key == 'vol x':
				_def_volx = value
			elif key == 'passed x':
				_def_passedx = value
			elif key == 'artist x':
				_def_artistx = value
			elif key == 'song x':
				_def_songx = value
			elif key == 'status x':
				_def_statusx = value
			elif key == 'dir y':
				_def_diry = value
			elif key == 'play y':
				_def_playy = value
			elif key == 'vol y':
				_def_voly = value
			elif key == 'passed y':
				_def_passedy = value
			elif key == 'artist y':
				_def_artisty = value
			elif key == 'song y':
				_def_songy = value
			elif key == 'status y':
				_def_statusy = value

	_fnt = (_fnt, _fnt_size)
	return _def_dirx, _def_playx, _def_songx, _def_volx, _def_passedx, _def_artistx, _def_statusx, _def_diry, _def_playy, _def_songy, _def_voly, _def_passedy, _def_artisty, _def_statusy, _fg, _bg, _fnt, _music_user_directory, _logo2_directory, _logo3_directory
try:
	_def_dirx, _def_playx, _def_songx, _def_volx, _def_passedx, _def_artistx, _def_statusx, _def_diry, _def_playy, _def_songy, _def_voly, _def_passedy, _def_artisty, _def_statusy, _fg, _bg, _fnt, _music_user_directory, _logo2_directory, _logo3_directory = readFromConfig()

except UnboundLocalError:

	_fg = 'red'
	_bg = 'red'
	_fnt = ('misc fixed', 1)
	_music_user_directory = Path.home()
	_logo3_directory = Path.home() / '.config' / 'graphite' / 'logo2.png'
	_logo2_directory = Path.home() / '.config' / 'graphite' / 'logo3.png'
	_notifications = 0

	_def_dirx = -50
	_def_playx = -50
	_def_volx = -50
	_def_passedx = -50
	_def_artistx = -50
	_def_songx = -50
	_def_statusx = -50

	_def_diry = -50
	_def_playy = -50
	_def_voly = -50
	_def_passedy = -50
	_def_artisty = -50
	_def_songy = -50
	_def_statusy = -50

_graphite_version = 'graphite [1.6]' # graphite version

# greet message

print(f"{str(sys.argv[0]).strip()} on {_graphite_version}")

# declare important variables

start_geo = "230x230"
if _bg == "white":
	_logo = f'{_logo3_directory}'
	_cur_logo = f'{_logo3_directory}'
else:
	_logo = f'{_logo2_directory}'
	_cur_logo = f'{_logo2_directory}'

_glb_vol = Decimal('1.00')
_sel_sng = None
_pus = False
_ply = False
_sng_raw_nme = None
_sng_lst = []						#_sng_lst[0] will be the name of the first song, [1] the second, and so on.
_cur_inx = 0						#the current song number, use it like "str(_sng_lst[_cur_inx])" (will give song name)
_art_nme = None
_repeat = False
_shuffle = False
_tinytag = None
_ui_state = 2

_dos = Tk()						# sets window
_dos.geometry(str(start_geo))				# sets starting geometry
_dos.title('graphite')					# sets window title to graphite	
icon = PhotoImage(file=f'{_logo2_directory}')		# sets icon to graph_logo2.png from graphite-app folder. you can put your image here.
_dos.iconphoto(True,icon)				# sets window logo to icon
_dos.config(background=_bg)				# sets window background to standard background, at the start it is 'white'
_dos.resizable(False,False)				# you cannot resize _dos when this is uncommented.
							# ^if you are using a wayland compositor like hyprland or any other wm that automatically tiles windows,
							# ^set it to false. its gonna keep it always floating. or just set a window rule in your 
							# compositor.
							# fuck graphite

# width, xaxis, height, yaxis

cover_w = 160
cover_x = 35
cover_h = 160
cover_y = 35

cover_label = Label(_dos,takefocus=0,bg=_bg)
cover_label.place(x=cover_x,y=cover_y)

def displayLogo(lgo):
	global _cur_logo
	_cur_logo = lgo

	cover = Image.open(lgo)
	cover = cover.resize((cover_w, cover_h), Image.Resampling.BILINEAR)
	cover = ImageTk.PhotoImage(cover)
	cover_label.config(image=cover)
	cover_label.image = cover
	cover_path = None

def songTime():
	global _sel_sng, _ply
	if _sel_sng:
		audio = File(_sel_sng)

		ntime = pygame.mixer.music.get_pos() / 1000
		elapsed = time.strftime('%M:%S', time.gmtime(ntime))
		ail = audio.info.length
		naudio = time.strftime('%M:%S', time.gmtime(ail))
		to_print = (elapsed + '/' + naudio)
		passed_label.config(text=to_print)
	_dos.after(80,songTime)

songTime()
displayLogo(_logo)

# or not, idk

dir_label = Label(_dos,text='file',font=_fnt,fg=_fg,cursor='hand2',bg=_bg)
play_button = Label(_dos,text='play/stop',font=_fnt,fg=_fg,cursor='hand2',bg=_bg)
vol_button = Label(_dos,text=str(_glb_vol),font=_fnt,fg=_fg,cursor='hand2',bg=_bg)
passed_label = Label(_dos,text='00:00/00:00',fg=_fg,bg=_bg,font=_fnt,cursor='hand2')
artist_label = Label(_dos,text='',fg=_fg,bg=_bg,font=_fnt)
_song_label = Label(_dos,fg=_fg,bg=_bg,text='',font=_fnt)
status_label = Label(_dos,fg=_fg,bg=_bg,text='',font=_fnt)

dir_label.place(x=_def_dirx,y=_def_diry)
play_button.place(x=_def_playx,y=_def_playy)
vol_button.place(x=_def_volx,y=_def_voly)
passed_label.place(x=_def_passedx,y=_def_passedy,anchor='e')
_song_label.place(x=_def_songx,y=_def_songy)
artist_label.place(x=_def_artistx,y=_def_artisty)
status_label.place(x=_def_statusx,y=_def_statusy)

def fileExists(file):
	if os.path.exists(file):
		return True
	elif not os.path.exists(file):
		print(f"error: file does not exist.\n^ {file}")
		return False

def getFiles(button,playlist,plfile):
	global _sel_sng,_sng_lst,_cur_inx,_pus,_ply,artist_label,file_extension,_sng_raw_nme,_art_nme,song_path,_graphite,cover_w,cover_h,_music_user_directory,cover_path,_notifications

	if playlist == False:
		if button == 1:

			if _music_user_directory.startswith("~"):
				_music_user_directory = _music_user_directory.replace("~", f"{Path.home()}", 1)

			path = filex(_music_user_directory,False)
			if _music_user_directory == path:
				return
			elif _sel_sng != None and os.path.dirname(_sel_sng) == path:
				return
		elif button == 0:
			path = os.getcwd()
		elif button == 5: 
			for i in _arg_lst:
				if i.startswith("--dir="):
					path = i.split("--dir=")[1]
					if path.startswith('~') == True:
						path = path.replace("~", f"{Path.home()}", 1)
	subprocess.run("clear")

	files = []
	files_cover = []

	if playlist == False:
		if path:
			files = sorted([f for f in os.listdir(path) if f.endswith(('.mp3','.wav','.ogg','.flac','.aac','.m4a','.alac'))])
			files_cover = [f for f in os.listdir(path) if f.lower().endswith(('.jpg','.png'))]
	else:
		#This will allow us to read the paths of songs from the user's selected playlist.
		#The user can right click on a file in filex to add it to the playlist.

		with open(plfile, 'r') as f:
			for line in f:
				lne = (str(line)).strip('\n')
				if lne.endswith(('.mp3','.wav','.ogg','.flac','.aac','.m4a','.alac')):
					if fileExists(lne):
						files.append(lne)
				elif lne.endswith(('.jpg','.png')):
					if fileExists(lne):
						files_cover.append(lne)

	try:
		if files:
			if playlist == False:
				_sng_lst = [os.path.join(path, f) for f in files]
			else:
				_sng_lst = files
			if len(_sng_lst) > 0:
				_cur_inx = 0
				_sel_sng = _sng_lst[_cur_inx]
				_sng_raw_nme, file_extension = os.path.splitext(os.path.basename(_sel_sng))
				pygame.mixer.music.stop()
				_pus = False

				_tinytag = TinyTag.get(_sel_sng)
				print(f"{_tinytag.year} - {_tinytag.album} by {_tinytag.artist}")

				for f in _sng_lst:
					if playlist == True:
						print(f"p       {os.path.basename(f)}")
					else:
						print(f"\t{os.path.basename(f)}")
			else:
				printf("error: no songs in song list.")
		else:
			_cur_inx = 0
			_sng_lst = []
			_sel_sng = None
			_song_label.config(text='no songs')
			pygame.mixer.music.stop()
			_pus = False

	except Exception as e:
		print(f"error: {e}")

	if files_cover:
		if playlist == False:
			cover_file = os.path.join(path, files_cover[0])
		else:
			cover_file = str(files_cover[0]).strip()
		try:
			displayLogo(cover_file)
		except Exception as e:
			pass
	else:
		displayLogo(_logo2_directory)
	
	if len(_sng_lst) > 0:
		playThisSong()

	updateInformation()

def filex(_filex_path,playlist):
	global _fg, _bg, _fnt, _playlist_folder

	_cur_dir = getListeningDir()
	if playlist == False:
		if _cur_dir != None:
			_filex_path = _cur_dir
	else:
		_cur_dir = _filex_path
	_pl_to_return = "graphite"
	_dosw = 350
	_dosh = 450
	_shdots = False
	_label_lst = []

	if _cur_dir != None:
		_filex_path = _cur_dir
	else:
		pass

	_dos2 = Toplevel(_dos)
	_dos2.geometry(f"{_dosw}x{_dosh}")
	_dos2.resizable(False,False)
	_dos2.config(bg=_bg)

	if playlist == False:
	
		_return = Label(_dos2, fg=_fg,bg=_bg,font=_fnt,text="<-",cursor='hand2')
		_return.place(x=5,y=5)
		_return.bind('<Enter>', lambda event: _return.config(fg='grey'))
		_return.bind('<Leave>', lambda event: _return.config(fg=_fg))
		_return.bind('<Button-1>', lambda event: retur())
	
		_ok = Label(_dos2, fg=_fg,bg=_bg,font=_fnt,text="ok",cursor='hand2')
		_ok.place(x=25,y=5)
		_ok.bind('<Enter>', lambda event: _ok.config(fg='grey'))
		_ok.bind('<Leave>', lambda event: _ok.config(fg=_fg))
		_ok.bind('<Button-1>', lambda event: end_filex(False,None))

		_new = Label(_dos2,fg=_fg,bg=_bg,font=_fnt,text="new",cursor='hand2')
		_new.place(x=45,y=5)
		_new.bind('<Enter>', lambda event: _new.config(fg='grey'))
		_new.bind('<Leave>', lambda event: _new.config(fg=_fg))
		_new.bind('<Button-1>', lambda event: make_playlist())

		_ent = Entry(_dos2,fg=_fg,bg=_bg,bd=0,highlightcolor=_fg,highlightbackground=_fg,font=_fnt)

	def create_playlist():
		nonlocal _filex_path, _ent

		_playlist_name = str(_ent.get())
		if _playlist_name != None:
			subprocess.run([f'touch \"{os.path.join(_filex_path, _playlist_name)}\"'], shell=True)
			print(f"created file at;   {os.path.join(_filex_path, _playlist_name)}")
		_ent.place(y=10000)
		_ent.delete(0, END)
		_dos2.title(f"{_filex_path}")
		shfiles()

	def make_playlist():
		nonlocal _filex_path, _dosh, _ent

		_filex_path = _playlist_folder
		shfiles()
		_dos2.title(f"creating playlist at {_filex_path}")
		_ent.place(x=(_dosw / 2) - 50,y=(_dosh / 2) - 10,width=100,height=20)
		_ent.bind('<Return>', lambda event: create_playlist())

	def end_filex(playlist,plname):
		nonlocal _pl_to_return
		if playlist == True:
			_pl_to_return = plname
		_dos2.destroy()

	def retur():
		nonlocal _filex_path
		_filex_path = os.path.dirname(_filex_path)
		shfiles()
	
	def shdots():
		nonlocal _shdots

		if _shdots == True:
			_shdots = False
		elif _shdots == False:
			_shdots = True

		shfiles()
	
	def shfiles():
		nonlocal _label_lst, _shdots, _filex_path, _dosh, playlist

		if playlist == False:
			offset_y = 20
			_dos2.title(f'{_filex_path}')
		elif playlist == True:
			offset_y = 0
			_dos2.title("choose a playlist")

		if _shdots == False:
			_file_lst = sorted([f for f in os.listdir(_filex_path) if not f.startswith('.')])
		else:
			_file_lst = sorted([f for f in os.listdir(_filex_path)])

		if len(_label_lst) > 0:
			for i in _label_lst:
				i.destroy()
	
			_label_lst.clear()
	
		def change_path(path,file):
			nonlocal _filex_path

			if os.path.isdir(os.path.join(_filex_path, file)) == True:
				_filex_path = path
				shfiles()
			else:
				print('not a directory')
	
		for f in _file_lst:
			_file_label = Label(_dos2, text=f,fg=_fg,bg=_bg,font=_fnt,cursor='hand2')
			_label_lst.append(_file_label)
		
		for i in _label_lst:
			i.place(x=10,y=(10 + offset_y))
			i.bind('<Enter>', lambda event, it=i: it.config(fg='grey'))
			i.bind('<Leave>', lambda event, it=i: it.config(fg=_fg))
			if playlist == False:
				i.bind('<Button-1>', lambda event, it=i: change_path(os.path.join(_filex_path, it.cget('text')), str(it.cget('text'))))
				if str(i.cget('text')).endswith(('.mp3','.wav','.ogg','.flac','.aac','.m4a','.alac','.png','.jpg')):
					i.bind('<Button-3>', lambda event, it=i: writeToPlaylist(os.path.join(_filex_path, it.cget('text'))))
			else:
				i.bind('<Button-1>', lambda event, it=i: end_filex(True, str(os.path.join(_filex_path, it.cget('text')))))

			_place_info = i.place_info()
			_dos2.geometry(f'{_dosw}x{int(_place_info['y']) + 22}')
			_dosh = (int(_place_info['y']) + 22)
			offset_y += 15

		offset_y = 0
		_file_lst = []
	
	shfiles()
	_dos2.bind('<period>', lambda event: shdots())
	_dos.wait_window(_dos2)
	if playlist == False:
		return _filex_path
	elif playlist == True:
		return _pl_to_return

def getListeningDir():
	try:
		dirname = os.path.dirname(_sng_lst[_cur_inx].strip())
		return dirname
	except IndexError:
		dirname = None
		return dirname

def playlistMenu(playit):
	global _playlist_folder
	playlisterer = filex(_playlist_folder,True)
	if playlisterer == None:
		return None
	if playit == True:
		getFiles(0,True,playlisterer)
	return playlisterer

#writetoplaylist

def modifyFile(file, mode, content):
	if os.path.isdir(file) == False:
		_which_pl = playlistMenu(False)
		with open(_which_pl, 'a') as p:
			p.write(f"\n{file}")
		print(f"writing {file} --> {_which_pl}")
	else:
		print(f"cannot write, {file} is a directory.")

def playThisSong():
	global _pus, _ply, _cur_inx, file_extension, _sng_raw_nme, song_path, _notifications, cover_path
	if _sel_sng:
		pygame.mixer.music.load(_sel_sng)
		pygame.mixer.music.set_volume(float(_glb_vol))
		pygame.mixer.music.play()
		_pus = False
		_ply = True
		_sng_raw_nme, file_extension = os.path.splitext(str(os.path.basename(_sel_sng)))

		_tinytag = TinyTag.get(str(_sel_sng))
		_art_nme = _tinytag.artist
		artist_label.config(text=str(_art_nme.lower()))
		_song_label.config(text=str(_sng_raw_nme.lower()))
		_dos.title(f'{_sng_raw_nme.lower()}')
		modifyStatus(_sng_raw_nme.lower())

	if _notifications == 1:
		subprocess.run(["notify-send", f"{_sng_raw_nme} - {_art_nme}", "-i", cover_path], shell=True)

def playEvent(event=None):
	global _song_label,_pus,_ply,_art_nme
	if _pus:
		pygame.mixer.music.unpause()
		play_button.config(fg=_fg)
		_pus = False
		_ply = True
	elif _ply:
		pygame.mixer.music.pause()
		_pus = True
		_ply = False
	else:
		if not _sel_sng:
			_song_label.config(text='no files given')
			return
		else:
			playThisSong()


def volumeEvent(event,incdec):
	global _glb_vol,vol_button
	
	if incdec == 0:
		if _glb_vol < Decimal('1.00'):
			_glb_vol += Decimal('0.05')
			pygame.mixer.music.set_volume(float(_glb_vol))
			vol_button.config(text=str(_glb_vol))
	elif incdec == 1:
		if _glb_vol > Decimal('0.00'):
			_glb_vol -= Decimal('0.05')
			pygame.mixer.music.set_volume(float(_glb_vol))
			vol_button.config(text=str(_glb_vol))

def skipEvent(event,state):
	global _glb_vol, _cur_inx, _sel_sng
	if state == "back":
		if _cur_inx - 1 >= 0:
			_cur_inx -= 1
			_sel_sng = _sng_lst[_cur_inx]
			playThisSong()
	elif state == "forward":
		if _cur_inx + 1 < len(_sng_lst):
			_cur_inx += 1
			_sel_sng = _sng_lst[_cur_inx]
			playThisSong()

def updateInformation():
	global _ply, _pus, _sel_sng, _cur_inx, _sng_lst, play, _ply_info, _art_nme

	if _ply:
		if pygame.mixer.music.get_busy():
			pass
		elif not _pus:
			if _repeat == True:
				_sel_sng = _sng_lst[_cur_inx]
				playThisSong()
			else:
				if _cur_inx + 1 < len(_sng_lst):
					_cur_inx += 1
					_sel_sng = _sng_lst[_cur_inx]
					playThisSong()
				else:
					_cur_inx = 0
					_sel_sng = _sng_lst[_cur_inx]
					playThisSong()
			if _shuffle == True:
				random_number = random.randint(0,len(_sel_sng))
				_sel_sng = _sng_lst[random_number]
				_cur_inx = random_number
				playThisSong()

	if _ply == True:
		play_button.config(text='stop')
	elif _pus == True:
		play_button.config(text='play')
	elif _pus == False and _ply == False:
		play_button.config(text='play')

	_dos.after(100, updateInformation)

def changeUiState():
	global _ui_state, _cur_logo, cover_x, cover_y, cover_w, cover_h, cover_label

	if _ui_state == 1:

		cover_x = 35
		cover_y = 35
		cover_w = 160
		cover_h = 160
		cover_label.place(x=cover_x,y=cover_y)

		displayLogo(_cur_logo)

		dir_label.place(x=_def_dirx,y=_def_diry)
		play_button.place(x=_def_playx,y=_def_playy)
		vol_button.place(x=_def_volx,y=_def_voly)
		passed_label.place(x=_def_passedx,y=_def_passedy,anchor='e')
		_song_label.place(y=_def_songy)
		artist_label.place(y=_def_artisty)
		status_label.place(y=_def_statusy)

		_ui_state = 2
	elif _ui_state == 2:
		_song_label.place(y=0)
		artist_label.place(y=1000)
		_ui_state = 3
	elif _ui_state == 3:
		_song_label.place(y=1000)
		artist_label.place(y=0)
		_ui_state = 4
	elif _ui_state == 4:
		_song_label.place(y=1000)
		artist_label.place(y=1000)
		_ui_state = 5
	elif _ui_state == 5:
		dir_label.place(x=0,y=1000)
		play_button.place(y=1000)
		vol_button.place(y=1000)
		passed_label.place(x=115,y=224,anchor='c')
		_song_label.place(y=1000)
		artist_label.place(y=1000)
		status_label.place(y=1000)
		_ui_state = 6
	elif _ui_state == 6:
		passed_label.place(y=1000)
		_ui_state = 7
	elif _ui_state == 7:

		cover_x = -1
		cover_y = -1
		cover_w = 230
		cover_h = 230

		cover_label.place(x=cover_x,y=cover_y)
		displayLogo(_cur_logo)

		_ui_state = 1

def switchState(event,state):
	global _repeat, _shuffle

	if state == 'repeat':
		_shuffle = False
		if _repeat == False:
			_repeat = True
			status_label.config(text='R')
		elif _repeat == True:
			_repeat = False
			status_label.config(text=' ')
	elif state == 'shuffle':
		_repeat = False
		if _shuffle == False:
			_shuffle = True
			status_label.config(text='S')
		elif _shuffle == True:
			_shuffle = False
			status_label.config(text=' ')

dir_label.bind('<Button-1>', lambda event: getFiles(1,False,None))
dir_label.bind('<Enter>', lambda event: dir_label.config(fg='grey'))
dir_label.bind('<Leave>', lambda event: dir_label.config(fg=_fg))
play_button.bind('<Button-1>',playEvent)
play_button.bind('<Enter>',lambda event: play_button.config(fg='grey'))
play_button.bind('<Leave>',lambda event: play_button.config(fg=_fg))
vol_button.bind('<Button-4>', lambda event: volumeEvent(None,0))
vol_button.bind('<Button-5>', lambda event: volumeEvent(None,1))
vol_button.bind('<Enter>', lambda event: vol_button.config(fg='grey'))
vol_button.bind('<Leave>', lambda event: vol_button.config(fg=_fg))
passed_label.bind('<Enter>', lambda event: passed_label.config(fg='grey'))
passed_label.bind('<Leave>', lambda event: passed_label.config(fg=_fg))
_dos.bind('<Tab>', lambda event: getFiles(1,False,None))
_dos.bind('<space>', playEvent)
_dos.bind('<Up>', lambda event: volumeEvent(None,0))
_dos.bind('<Down>', lambda event: volumeEvent(None,1))
_dos.bind('<Right>', lambda event: skipEvent(None,"forward"))
_dos.bind('<Left>', lambda event: skipEvent(None,"back"))
_dos.bind('<KeyPress-g>', lambda event: changeUiState())
_dos.bind('<KeyPress-p>', lambda event: playlistMenu(True))
_dos.bind('<KeyPress-r>', lambda event: switchState(None,"repeat"))
_dos.bind('<KeyPress-s>', lambda event: switchState(None,"shuffle"))

updateInformation()
_dos.mainloop()

