#!/bin/python3

from tkinter import *
from tinytag import TinyTag
import tkinter as tk
from decimal import Decimal
from mutagen import File
from PIL import Image, ImageTk
from pathlib import Path
import time, pygame, os, subprocess, sys, random

subprocess.run('clear')

pygame.init()
pygame.mixer.init()

home_path = Path.home()
app_path = home_path / '.config' / 'graphite'
config_path = app_path / 'graphite.conf'
playlist_path = app_path / 'playlist.conf'

def read_settings():
	global _notifications
	with open(config_path, 'r') as cfg:
		for line in cfg:
			if ':' not in line:
				continue
			key, value = line.split(':', 1)
			key = key.strip()
			value = value.strip()			
		
			if key == 'foreground':
				_fg = str(value)
			elif key == 'background':
				_bg = str(value)
			elif key == 'font':
				_fnt = (str(value), 10)
			elif key == 'directory to choose music from':
				_music_user_directory = str(value)
			elif key == 'logo2 directory':
				_logo2_directory = value
			elif key == 'logo3 directory':
				_logo3_directory = value
			elif key == 'send notifs on song play':
				_notifications = int(value)

	return _fg, _bg, _fnt, _music_user_directory, _logo2_directory, _logo3_directory

try:
	_fg, _bg, _fnt, _music_user_directory, _logo2_directory, _logo3_directory = read_settings()
except UnboundLocalError:
	_fg = 'black'
	_bg = 'white'
	_fnt = ('misc fixed', 10)
	_music_user_directory = Path.home()
	_logo2_directory = Path.home() / '.config' / 'graphite' / 'logo2.png'
	_logo3_directory = Path.home() / '.config' / 'graphite' / 'logo3.png'
	_notifications = 0

gver = 'graphite [1.3]' # graphite version

start_geo = "230x230"
_logo = f'{_logo2_directory}'
_glb_vol = Decimal('1.00')
_sel_sng = None
_pus = False
_ply = False
_hvr = False
_sng_raw_nme = None
_sng_lst = []						#_sng_lst[0] will be the name of the first song, [1] the second, and so on.
_cur_inx = 0						#the current song number, use it like "str(_sng_lst[_cur_inx])" (will give song name)
_art_nme = None
_repeat = False
_shuffle = False
ttag = None
_ui_state = 2

_dos = Tk()						#sets window
_dos.geometry(str(start_geo))				#sets starting geometry
_dos.title('graphite')					#sets window title to graphite	
icon = PhotoImage(file=f'{_logo2_directory}')		#sets icon to graph_logo2.png from graphite-app folder. you can put your image here.
_dos.iconphoto(True,icon)				#sets window logo to icon
_dos.config(background=_bg)				#sets window background to standard background, at the start it is 'white'
_dos.resizable(False,False)				#you cannot resize _dos when this is uncommented.
							#^if you are using a wayland compositor like hyprland or any other wm that automatically tiles windows,
							#^set it to false. its gonna keep it always floating. (or just set a window rule in your compositor)

cover_w = 160   #150
cover_x = 35    #37.5
cover_h = 160   #150
cover_y = 35    #50
cover_label = Label(_dos,takefocus=0,bg=_bg)
cover_label.place(x=cover_x,y=cover_y)

cover = Image.open(_logo)
cover = cover.resize((cover_w, cover_h), Image.Resampling.LANCZOS)
cover = ImageTk.PhotoImage(cover)
cover_label.config(image=cover)
cover_label.image = cover
cover_path = None

def song_time():
	global _sel_sng, _ply
	if _sel_sng:
		audio = File(_sel_sng)

		ntime = pygame.mixer.music.get_pos() / 1000
		elapsed = time.strftime('%M:%S', time.gmtime(ntime))
		ail = audio.info.length
		naudio = time.strftime('%M:%S', time.gmtime(ail))
		to_print = (elapsed + '/' + naudio)
		passed_label.config(text=to_print)
	_dos.after(80,song_time)
song_time()

#set some labels and where they are supposed to be placed, i as in xtn am considering
#to move to relx() instead of x=foo.

dir_label = Label(_dos,text='file',font=_fnt,fg=_fg,cursor='hand2',bg=_bg)
play_button = Label(_dos,text='play/stop',font=_fnt,fg=_fg,cursor='hand2',bg=_bg)
vol_button = Label(_dos,text=str(_glb_vol),font=_fnt,fg=_fg,cursor='hand2',bg=_bg)
passed_label = Label(_dos,text='00:00/00:00',fg=_fg,bg=_bg,font=_fnt,cursor='hand2')
artist_label = Label(_dos,text='',fg=_fg,bg=_bg,font=_fnt)
song_name = Label(_dos,fg=_fg,bg=_bg,text='',font=_fnt)
repeat_label = Label(_dos,fg=_fg,bg=_bg,text='',font=_fnt)

dir_label.place(x=0,y=215)
play_button.place(x=35,y=215)
vol_button.place(x=105,y=215)
passed_label.place(x=230,y=224,anchor='e')
song_name.place(x=0,y=0)
artist_label.place(x=0,y=13)
repeat_label.place(x=220,y=0)

def filex(thing):
	global _fg, _bg, _fnt
	
	_conf_path = Path.home() / '.config' / 'graphite' / 'graphite.conf'
	_shdots = False
	_label_lst = []

	_dos2 = Toplevel(_dos)
	_dos2.geometry("450x350")
	_dos2.resizable(False,False)
	_dos2.config(bg=_bg)

#	Had issues with dir_label
#	_dos2.grab_set()

	_return = Label(_dos2, fg=_fg,bg=_bg,font=_fnt,text="<-",cursor='hand2')
	_return.place(x=5,y=5)
	_return.bind('<Enter>', lambda event: _return.config(fg='grey'))
	_return.bind('<Leave>', lambda event: _return.config(fg=_fg))
	_return.bind('<Button-1>', lambda event: retur())
	
	_ok = Label(_dos2, fg=_fg,bg=_bg,font=_fnt,text="ok",cursor='hand2')
	_ok.place(x=25,y=5)
	_ok.bind('<Enter>', lambda event: _ok.config(fg='grey'))
	_ok.bind('<Leave>', lambda event: _ok.config(fg=_fg))
	_ok.bind('<Button-1>', lambda event: end_file())	

	def end_file():
		_dos2.destroy()
	
	def retur():
		nonlocal thing
		thing = os.path.dirname(thing)
		shfiles()
	
	def shdots():
		nonlocal _shdots

		if _shdots == True:
			_shdots = False
		elif _shdots == False:
			_shdots = True

		shfiles()
	
	def shfiles():
		nonlocal _label_lst, _shdots, thing

		_dos2.title(f'{thing}')

		if _shdots == False:
			_file_lst = sorted([f for f in os.listdir(thing) if not f.startswith('.')])
		else:
			_file_lst = sorted([f for f in os.listdir(thing)])
			
		offset_y = 20
	
		if len(_label_lst) > 0:
			for i in _label_lst:
				i.destroy()
	
			_label_lst.clear()
	
		def change_path(path,file):
			nonlocal thing

			if os.path.isdir(os.path.join(thing, file)) == True:
				thing = path
				shfiles()
			else:
				print('not a directory')
	
		for f in _file_lst:
			_file_label = Label(_dos2, text=f,bg=_bg,fg=_fg,font=_fnt,cursor='hand2')
			_label_lst.append(_file_label)
		
		for i in _label_lst:
			i.place(x=10,y=(10 + offset_y))
			i.bind('<Enter>', lambda event, it=i: it.config(fg='grey'))
			i.bind('<Leave>', lambda event, it=i: it.config(fg=_fg))
			i.bind('<Button-1>', lambda event, it=i: change_path(os.path.join(thing, it.cget('text')), str(it.cget('text'))))

			_place_info = i.place_info()
			_dos2.geometry(f'450x{int(_place_info['y']) + 22}')

			offset_y += 15

		offset_y = 0
		_file_lst = []
	
	shfiles()
	_dos2.bind('<period>', lambda event: shdots())
	_dos.wait_window(_dos2)
	return thing

def get_files(button,playlist):
	global _sel_sng,_sng_lst,_cur_inx,_hvr,_pus,_ply,artist_label,file_extension,_sng_raw_nme,_art_nme,song_path,app_path,cover_w,cover_h,_music_user_directory,cover_path,_notifications

	if playlist == False:
		if button == 1:
			# As promised, peak of my creativity.
			path = filex(_music_user_directory)
		elif button == 0:
			path = os.getcwd()
		elif button == 5: 
			for i in _arg_lst:
				if i.startswith("--dir="):
					path = i.split("--dir=")[1]
					if path.startswith('~') == True:
						path = path.replace("~", f"{Path.home()}", 1)
	files = []
	files_covert = []

	if playlist == False:
		if path:
			files = sorted([f for f in os.listdir(path) if f.endswith(('.mp3','.wav','.ogg','.flac','.aac','.m4a','.alac'))])
			files_covert = [f for f in os.listdir(path) if f.lower().endswith(('.jpg','.png'))]
	else:
		#This will allow us to read the specific and absolute paths of a file from ~/.config/graphite/playlist.conf
		#Later in the production of graphite i will lean towards a program, or just graphite, that helps the user choose the songs
		#and write the paths to the playlist just like in cmus with "add {directory}"

		with open(playlist_path, 'r') as f:
			for line in f:
				lne = (str(line)).strip('\n')
				if lne.endswith(('.mp3','.wav','.ogg','.flac','.aac','.m4a','.alac')):
					files.append(lne)
				elif lne.endswith(('.jpg','.png')):
					files_covert.append(lne)

	if files:
		if playlist == False:
			_sng_lst = [os.path.join(path, f) for f in files]
		else:
			_sng_lst = files			
		_sel_sng = _sng_lst[_cur_inx]
		_sng_raw_nme, file_extension = os.path.splitext(os.path.basename(_sel_sng))
		pygame.mixer.music.stop()
		_hvr = False
		_pus = False
		_cur_inx = 0
	else:
		_sng_lst = []
		_sel_sng = None
		song_name.config(text='no audio :^(')
	if files_covert:
		covert_file = os.path.join(path, files_covert[0])
		cover_path = str(covert_file)
		try:
			cover = Image.open(covert_file)
			cover = cover.resize((cover_w, cover_h), Image.Resampling.LANCZOS)
			cover = ImageTk.PhotoImage(cover)

			cover_label.config(image=cover)
			cover_label.image = cover
		except Exception as e:
			pass
	else:
		cover_path = f'{_logo2_directory}'
		cover = Image.open(f'{_logo2_directory}')
		cover = cover.resize((cover_w, cover_h), Image.Resampling.LANCZOS)
		cover = ImageTk.PhotoImage(cover)

		cover_label.config(image=cover)
		cover_label.image = cover
	
	if len(_sng_lst) > 0:
		play_this_song()

	update_ply_info()

def play_this_song():
	global _pus, _ply, _cur_inx, file_extension, _sng_raw_nme, song_path, _notifications, cover_path
	if _sel_sng:
		pygame.mixer.music.load(_sel_sng)
		pygame.mixer.music.set_volume(float(_glb_vol))
		pygame.mixer.music.play()
		_pus = False
		_ply = True
		_sng_raw_nme, file_extension = os.path.splitext(str(os.path.basename(_sel_sng)))

		ttag = TinyTag.get(str(_sel_sng))
		_art_nme = ttag.artist
		artist_label.config(text=str(_art_nme.lower()))
		song_name.config(text=str(_sng_raw_nme.lower()))
		_dos.title(f'{_sng_raw_nme.lower()}')

	if _notifications == 1:
		subprocess.run(["notify-send", f"{_sng_raw_nme} - {_art_nme}", "-i", cover_path], shell=True)

def play_click(event=None):
	global _sel_sng, _pus, _ply, _art_nme
	if not _sel_sng:
		song_name.config(text='no files given')
		return
	else:
		play_this_song()
def play_button_(event=None):
	global song_name,_pus,_ply,_art_nme
	if _pus:
		pygame.mixer.music.unpause()
		play_button.config(fg=_fg)
		_pus = False
		_ply = True
	elif _ply:
		pygame.mixer.music.pause()
		_pus = True
		_ply = False
	else:
		play_click()

def vol_click(event):
	global _glb_vol,vol_button
	if _glb_vol < Decimal('1.00'):
		_glb_vol += Decimal('0.05')
		pygame.mixer.music.set_volume(float(_glb_vol))
		vol_button.config(text=str(_glb_vol))
def vol_dec(event):
	global _glb_vol,vol_button
	if _glb_vol > Decimal('0.00'):
		_glb_vol -= Decimal('0.05')
		pygame.mixer.music.set_volume(float(_glb_vol))
		vol_button.config(text=str(_glb_vol))
def vol_scroll(event):
	if event.delta > 0:
		vol_click(event)
	else:
		vol_dec(event)

def skip_left_click(event):
	global _glb_vol,skip_left,_cur_inx,_sel_sng
	if _cur_inx - 1 >= 0:
		_cur_inx -= 1
		_sel_sng = _sng_lst[_cur_inx]
		play_this_song()
def skip_left_enter(event):
	global _hvr
	_hvr = True
	skip_left.config(fg='grey')
def skip_left_leave(event):
	global _hvr
	_hvr = False
	skip_left.config(fg=_fg)
def skip_right_click(event):
	global _glb_vol,skip_right,_cur_inx,_sel_sng
	if _cur_inx + 1 < len(_sng_lst):
		_cur_inx += 1
		_sel_sng = _sng_lst[_cur_inx]
		play_this_song()
def skip_right_enter(event):
	global _hvr
	_hvr = True
	skip_right.config(fg='grey')
def skip_right_leave(event):
	global _hvr
	_hvr = False
	skip_right.config(fg=_fg)

def update_ply_info():
	global _ply, _pus, _sel_sng, _cur_inx, _sng_lst, _hvr, play, next_song1, next_song2, next_song3, next_song4, next_song5, _ply_info, _art_nme

	if _ply:
		if pygame.mixer.music.get_busy():
			pass
		elif not _pus and not _hvr:
			if _repeat == True:
				_sel_sng = _sng_lst[_cur_inx]
				play_this_song()
			else:
				if _cur_inx + 1 < len(_sng_lst):
					_cur_inx += 1
					_sel_sng = _sng_lst[_cur_inx]
					play_this_song()
				else:
					_cur_inx = 0
					_sel_sng = _sng_lst[_cur_inx]
					play_this_song()
			if _shuffle == True:
				random_number = random.randint(0,len(_sel_sng))
				_sel_sng = _sng_lst[random_number]
				_cur_inx = random_number
				play_this_song()

	if _ply == True:
		play_button.config(text='stop')
	elif _pus == True:
		play_button.config(text='play')
	elif _pus == False and _ply == False:
		play_button.config(text='play')

	_dos.after(100, update_ply_info)

def hide_ui():
	global _ui_state

	if _ui_state == 1:
		dir_label.place(x=0,y=215)
		play_button.place(x=35,y=215)
		vol_button.place(x=105,y=215)
		passed_label.place(x=230,y=224,anchor='e')
		song_name.place(y=0)
		artist_label.place(y=13)
		_ui_state = 2
	elif _ui_state == 2:
		song_name.place(y=0)
		artist_label.place(y=1000)
		_ui_state = 3
	elif _ui_state == 3:
		song_name.place(y=1000)
		artist_label.place(y=0)
		_ui_state = 4
	elif _ui_state == 4:
		song_name.place(y=1000)
		artist_label.place(y=1000)
		_ui_state = 5
	elif _ui_state == 5:
		dir_label.place(x=0,y=1000)
		play_button.place(x=35,y=1000)
		vol_button.place(x=105,y=1000)
		passed_label.place(x=115,y=224,anchor='c')
		song_name.place(x=0,y=1000)
		artist_label.place(x=0,y=1000)
		_ui_state = 6
	elif _ui_state == 6:
		passed_label.place(y=1000)
		_ui_state = 1
def switch_r(event):
	global _repeat, _shuffle
	
	_shuffle = False
	if _repeat == False:
		_repeat = True
		repeat_label.config(text='R')
	elif _repeat == True:
		_repeat = False
		repeat_label.config(text=' ')
def switch_s(event):
	global _repeat, _shuffle

	_repeat = False
	if _shuffle == False:
		_shuffle = True
		repeat_label.config(text='S')
	elif _shuffle == True:
		_shuffle = False
		repeat_label.config(text=' ')

dir_label.bind('<Button-1>', lambda event: get_files(1,False))
dir_label.bind('<Enter>', lambda event: dir_label.config(fg='grey'))
dir_label.bind('<Leave>', lambda event: dir_label.config(fg=_fg))
play_button.bind('<Button-1>',play_button_)
play_button.bind('<Enter>',lambda event: play_button.config(fg='grey'))
play_button.bind('<Leave>',lambda event: play_button.config(fg=_fg))
vol_button.bind('<Button-4>', vol_click)
vol_button.bind('<Button-5>', vol_dec)
vol_button.bind('<Enter>', lambda event: vol_button.config(fg='grey'))
vol_button.bind('<Leave>', lambda event: vol_button.config(fg=_fg))
passed_label.bind('<Enter>', lambda event: passed_label.config(fg='grey'))
passed_label.bind('<Leave>', lambda event: passed_label.config(fg=_fg))
_dos.bind('<Tab>', lambda event: get_files(1,False))
_dos.bind('<space>', play_button_)
_dos.bind('<Up>', vol_click)
_dos.bind('<Down>', vol_dec)
_dos.bind('<Right>', skip_right_click)
_dos.bind('<Left>', skip_left_click)
_dos.bind('<KeyPress-g>', lambda event: hide_ui())
_dos.bind('<KeyPress-p>', lambda event: get_files(1,True))
_dos.bind('<KeyPress-r>', switch_r)
_dos.bind('<KeyPress-s>', switch_s)

if len(sys.argv) > 1:
	_arg_lst = []
	_get = 0

	for i in sys.argv[1:]:
		_arg_lst.append(i)

	if "--help" in _arg_lst:
		print("usage; graphite [--key=word]")
		print("options;")
		print("    --dir         [directory for music, can be a tree with folders with music]")
		print("    --shuffle     [immediately set shuffle on]")
		print("    --repeat      [immediately set repeat on]")
		print("    --help        [display this help and exit]")
		print("example; graphite --dir=~/mus/suicideboys/dsotc --shuffle")
		print("        ^ this will play \"Dark Side of the Clouds\" by $uicideboy$, and immediately shuffle the album.")
		sys.exit()

	for i in _arg_lst:
		if i.startswith("--dir="):
			_music_user_directory = i.split("--dir=")[1]
			_get = 1
		elif i == "--shuffle":
			switch_s(None)
		elif i == "--repeat":
			switch_r(None)
	
	if _get == 1:
		get_files(5,False)
	else:
		get_files(0,False)

update_ply_info()
_dos.mainloop()
